language: node_js
node_js:
- v7
- v6
- v5
- v4

before_install:
  - sudo apt-get -y install python2.7
  - sudo pip install -U setuptools
  - sudo pip install -U virtualenvwrapper
  - python -V
  - pip -V

install:
- pip install grow
- npm install -g yo
- npm link

script:
- yo grow --name yo-grow-site --description Testing --authorName Travis --authorEmail hello@grow.io --authorUrl grow.io --homepage grow.io --keywords testing
- grow build
